env:
    browser: true
    es6: true
extends:
    - eslint:recommended
    - airbnb-base
    - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
parserOptions:
    ecmaVersion: 2020
    sourceType: module
root: true
rules:
    import/extensions: [error, ignorePackages]
